### ISSUE TITLE
What Kindle version did you use?

### ISSUE THREAD

**Issue by tekknolagi** [DylanHamer/DebianKindle#4]
Is this only possible for a certain set of Kindles?

**Comment by DylanHamer** [comment]
Its possible with most of them, but I used a Kindle Touch 3

**Comment by tekknolagi** [comment]
Neat, thanks!

**Comment by tekknolagi** [comment]
Does it connect to wireless networks?

**Comment by DylanHamer** [comment]
Yep!

**Comment by tekknolagi** [comment]
Swell! Thanks a bunch.

**Comment by DylanHamer** [comment]
No problem. If you have any more questions, please PM [me](https://www.reddit.com/u/dylanhamer13) if you have anymore questions rather than using the issue tracker.
